### ISSUE TITLE
Ideas for testing LongPressable?

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d-react#17]
It doesn't seem like Enzyme can simulate long presses because it actually calls event callbacks instead of actually producing the event. Any ideas on how `LongPressable` can be tested?

Also, the tests don't seem to be running on my machine. I run `npm test` and it just freezes, do you know why?

**Comment by ChristopherChudzicki** [comment]
To be honest, I don't have a lot of experience with testing React components. For _most_ of the components in `math3d-react`, I'm not sure it's even worth writing tests. But I do agree that testing _this_ component is worthwhile.

So, I'll read about this a bit. (Though possibly not soon. Midterm comments are due Monday...)

Regarding `npm test`, you get no error messages?

Do you have `create-react-app` installed? Maybe try `create-react-app my-app`, `cd my-app`, `npm test`. I'm curious if that works?

**Comment by ChristopherChudzicki** [comment]
@stardust66 I'm going to close this issue. Let's move the discussion to #18
