### ISSUE TITLE
Unable to utilize inverse trig functions

### ISSUE THREAD

**Issue by SkylerLipthay** [ChristopherChudzicki/math3d-react#191]
For example, typing `arcsin` resolves to `arc sin` ("undefined symbol arc"). I think this is because auto-escaping gives `sin` precedence?

Apologies if this is a user error :) This is a fantastic tool, I'm in love with it.

**Comment by ChristopherChudzicki** [comment]
@SkylerLipthay Thanks for the issue! Yes, you're right. The functions `arcsin`, `arccos`, and `arctan` should work properly now.

Also, `arctan` can be called as `arctan(u)` or `arctan(y, x)`. (https://en.wikipedia.org/wiki/Atan2)

**Comment by SkylerLipthay** [comment]
Awesome! Thanks for the promptness. I'm glad it was a quick fix. This tool has really helped me in my studies.
