### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by NeatNit** [ChristopherChudzicki/math3d-react#196]
1. Go to https://www.math3d.org/NBtrlKbR
2. Try to Add object -> Vector (or anything else)
3. Crash, whole screen goes white

Console shows:

![image](https://user-images.githubusercontent.com/2400026/60129072-e4278b80-979c-11e9-9e55-1c5ef73a52e7.png)

**Comment by NeatNit** [comment]
Forgot to say: this happened after I used one of the examples as base, and added and deleted stuff from there. Might be some weird stuff that got carried over from an old version (when the examples were made) and can't be recreated in the current version.

**Comment by ChristopherChudzicki** [comment]
@NeatNit Thanks for this very clear bug report! I believe I have fixed the bug in #200. 

The new build just finished deploying, and https://www.math3d.org/NBtrlKbR is now working for me 😄
