### ISSUE TITLE
Color mapping - X, Y, Z go backwards

### ISSUE THREAD

**Issue by NeatNit** [ChristopherChudzicki/math3d-react#203]
Example: https://www.math3d.org/qQIkWGxv
![image](https://user-images.githubusercontent.com/2400026/60178483-555e5180-9824-11e9-94f9-13b15eb6cd78.png)

I expect Z=0 (red) to be where z is at its minimum (-5), and Z=1 (blue) to be where z is at its maximum (5). The result is the opposite.

**Comment by ChristopherChudzicki** [comment]
I just created #204 to address this.

It's not that X, Y, and Z go backward, it's that the color bar was opposite of what I intended. (Note that the red/blue map goes the as-advertised direction).

At least for the third colormap (internally, "temperature") this gives a 0=blue=cool, 1=red=warm correspondence.

**Comment by ChristopherChudzicki** [comment]
Resolved by #204
