### ISSUE TITLE
Feedback on readme

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d-react#226]
I went through the installation process in the README on my Mac. I have some comments:

### MongoDB
`brew install mongodb` does not work. Apparently `mongodb` is not an available formula. Instead, MongoDB has its own tap: https://github.com/mongodb/homebrew-brew. So we have to run
```bash
> brew tap mongodb/brew
> brew install mongodb-community
```
General instructions are here: https://docs.mongodb.com/manual/administration/install-community/

### Starting Server
The start script for the server requires `build/main.js`, so we need to run
```bash
> npm run build:server
```
first. Also, starting the server throws `MongoError: database name must be a string`. I changed the URI in `.env` to from `mongodb://localhost:27017` to `mongodb://localhost:27017/somename` and the server started no problem. I don't know if this is dependent on the version of MongoDB and if I've installed a different version.

### Client
In the final instruction
```bash
cd react-ui
```
should be
```bash
cd client
```

After making these changes I can set up and run the server and the client without issues.

**Comment by ChristopherChudzicki** [comment]
Thanks for reporting this! Glad you got it up and running. To be honest, I did not try installing fresh mongo and fresh repo clone, which was a bit lazy of me. I'll try this weekend.

Re 
> Also, starting the server throws MongoError: database name must be a string. I changed the URI in .env to from mongodb://localhost:27017 to mongodb://localhost:27017/somename and the server started no problem. 

Yeah, good catch.
