### ISSUE TITLE
copyright of generated plots

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [ChristopherChudzicki/math3d-react#231]
hi - I'd like to use a plot I created with the math3d website in a book I am writing on machine learning to illustrate the idea of local minima in a loss function.

Is there any copyright I need to be aware of, or need for attribution?

Thanks

image attached (will be added with text/arrows etc in book illustration)

<img width="1405" alt="local_minima" src="https://user-images.githubusercontent.com/17411198/72188485-5b97d200-33f2-11ea-9a06-785029243f48.png">

**Comment by ChristopherChudzicki** [comment]
No, you're free to use the plots for whatever you like. The webapp source code is also open-source under the MPL-2.0 license (https://github.com/ChristopherChudzicki/math3d-react/blob/master/LICENSE).

I'm glad you're finding the site useful. If you need more customization, you might check out the underlying graphics library (https://github.com/unconed/mathbox). (That library isn't particular well maintained; I am working on some updates and making it npm-compatible, email me at math3dapp@gmail.com if you want more info.)

If you end up using lots of plots from math3d.org, it'd be great to mention the site but you certainly are not under any obligation to do so. Or just tell your colleagues about it!

**Comment by makeyourownneuralnetwork** [comment]
thanks @ChristopherChudzicki
