### ISSUE TITLE
Protection against leaving page and losing work

### ISSUE THREAD

**Issue by davidaylaian** [ChristopherChudzicki/math3d-react#236]
I was writing my equations in Math3D when I accidentally hit backspace while no text boxes were selected. My browser (Firefox) sent me back to the previous page. When I went back to Math3D, my work was gone.

From this, I have two suggestions:
1. Suppress backspace going to the previous page (Desmos does this)
2. Before the page unloads, confirm that the user wants to leave: (Desmos does this also)

![Screenshot from 2020-01-27 09-20-35](https://user-images.githubusercontent.com/22228595/73182062-56bb6980-40e6-11ea-8598-db7d85795b8c.png)

Btw, very cool website!

**Comment by ChristopherChudzicki** [comment]
Thanks for the suggestion. I think this is a great idea and probably would not be too hard to implement.

**Comment by ChristopherChudzicki** [comment]
@davidaylaian Thanks again for this suggestion, and thanks @stardust66 for the initial implementation. This has been implemented by #239 and #240, so I am closing the issue.

If either of you are unhappy with the result, please feel free to reopen.
