### ISSUE TITLE
iso-lines / contour plots?

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [ChristopherChudzicki/math3d-react#238]
it would be amazing if math3d could plot iso-lines / contour plots.

I realise this is a 2d plot.

and apologies if it can do it and I haven't; found the documentation / example

**Comment by ChristopherChudzicki** [comment]
I don't think there's a way to get 2d contour-plots of `f(x,y)` right now. 

**Density Plots** However, you can use color maps to generate 2d density plots. Here's an example: https://www.math3d.org/MtnSQkL9 I do realize that contour plots can be easier to interpret sometimes. Of course, you could put the density plot on any surface using the color map, putting it on z=0 just reproduces classic 2d density plots.

**Re contour/isolines**: 
- adding constant x/y/z isolines to implicit surfaces would be great. You can sort of "see" these lines now at the intersection of faces (https://www.math3d.org/YmSpdYTH) but it would be great to add lines to show these more explicitly. (*Disclaimer* I have had less time to work on math3d lately, and probably can't do this soon.)
- I'm not sure the best way to do this in math3d with 2d plots. I mean feature-scope / planning / ui, not technical implementation. What plane would the 2d plot go on?

If you just need 2d contour plots online, Geogebra might have some useful functionality.

**Comment by makeyourownneuralnetwork** [comment]
thanks @ChristopherChudzicki - I appreciate your thoughts and you helpful example
