### ISSUE TITLE
Deleting variable with eval error causes crash

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d-react#250]
## Steps to reproduce
1. Create new variable or function.
2. Set it to `f(x) = e^y` which produces an eval error.
3. Delete variable.

Crash happens because an `UNSET_ERROR` is dispatched after the math object gets deleted, which tries to unset a property on the deleted math object. Checking if the target object is undefined (https://github.com/ChristopherChudzicki/math3d-react/commit/1796f01768ea3dc512f68c977e8928c04b16c10a) fixes this, but there's probably a better fix?

**Comment by ChristopherChudzicki** [comment]
Well… That’s not great. Thanks for tracking down the cause! My weekend is pretty full

**Comment by ChristopherChudzicki** [comment]
Well, that’s not great… Thanks for Tracking down the cause! That fix might be reasonable, but I do want to look into it at least briefly… My weekend is pretty full, but i’ll try to look into it in the next couple of days.
