### ISSUE TITLE
Vertical scroll ends before reaching the bottom

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d-react#259]
### Steps to reproduce
1. Create a line after the initial explicit surface.
2. Create explicit surfaces until the line goes out of view.
3. Try to scroll down. When scroll reaches the bottom, only the name of the line is visible.

![image](https://user-images.githubusercontent.com/11802391/88846091-1d59d880-d1b3-11ea-8026-975af32a7ed1.png)

This happens somewhat with other objects like explicit surfaces, but in that case only the bottom of the object is occluded so they are still usable.
![image](https://user-images.githubusercontent.com/11802391/88846725-07004c80-d1b4-11ea-8384-2016b1928540.png)

**Comment by ChristopherChudzicki** [comment]
Good find. The tabs header (with the "Add Object" button) looks taller to me than it used to. I be a minor version change in ant-design increased the tab header height. Maybe we should lock the antd version instead of allowing minor version bumps on install.

**Comment by ChristopherChudzicki** [comment]
@stardust66 I believe this was resolved by #271

**Comment by ChristopherChudzicki** [comment]
Sorry it took 5 months... i have no good excuse!

**Comment by stardust66** [comment]
No worries. I certainly could have looked into it more too.
