### ISSUE TITLE
Scene rotation breaks when there are a lot of items on the left and it is scrolled all the way down

### ISSUE THREAD

**Issue by toughengineer** [ChristopherChudzicki/math3d-react#269]
When there are a lot of items in the left thingy (in the linked example — a lot of points points) and it is scrolled all the way down, rotation of the scene (when you click on it and hold and move the cursor) becomes unreliable, which is very annoying.
https://www.math3d.org/uMgz4wJE

Workaround: scroll the left thingy up and scene rotation becomes reliable again.

**Comment by ChristopherChudzicki** [comment]
@toughengineer Thanks for reporting this! Sorry it took so long to get addressed.

This should be fixed now. If it is not, please feel free to reopen this issue.

**Comment by toughengineer** [comment]
@ChristopherChudzicki, no problem! It seems to work now.
Thanks for developing this great tool!
