### ISSUE TITLE
Bug in displaying Grid with custom divisions

### ISSUE THREAD

**Issue by MarksonChen** [ChristopherChudzicki/math3d-react#290]
For a grid with axes xy, when the division is the default [10,10], the grid looks fine:
![image](https://user-images.githubusercontent.com/46666959/118170209-ace91480-b3de-11eb-906c-4db24ff1b753.png)
However, when the division is changed to [20,20], the grid is not displayed properly: ([link](https://www.math3d.org/EvgkQmn3))
![image](https://user-images.githubusercontent.com/46666959/118170347-d3a74b00-b3de-11eb-9d09-c9e2f5d784f1.png)
The grid setting can be found at "Axes & Camera" -> "Axes and Grids" -> "Grid Axes: xy" -> settings

**Comment by ChristopherChudzicki** [comment]
The grids have an option "Snap" which supposedly

> Snap[s] [gridlines] to nice numbers

From [mathbox documentation](https://github.com/unconed/mathbox/blob/master/docs/primitives.md)

Which appears to be messing up your grid lines.

That said...

- I don't know what qualifies as a "nice number"
- math3d absolutely does not document this behavior very well

So I think the best thing to do is to just change the default value of "snap" from "true" to "False".

**Comment by ChristopherChudzicki** [comment]
@MarksonChen This should be fixed now that the default for grids is `snap: false`.
