### ISSUE TITLE
math3d.org is down

### ISSUE THREAD

**Issue by o-b-o** [ChristopherChudzicki/math3d-react#304]
I love this tool, it's my friend for every homework assignment I get. Please tell me this is just temporary.

**Comment by ChristopherChudzicki** [comment]
I'll look into the history, but it appears to be up. Are you still having trouble?

**Comment by ChristopherChudzicki** [comment]
Math3d is hosted on a fairly Heroku instance which apparently only keeps metrics for 24 hours. So I can't see too much of yesterday. But... it does seem to be up now.

**Comment by ChristopherChudzicki** [comment]
@o-b-o I'm going to close this, but feel free to open a new issue if still having trouble accessing the site.

**Comment by o-b-o** [comment]
Weird, it appears to be up on https://downforeveryoneorjustme.com/math3d.org unfortunately I can't access it. There must be something going on on my end. I'll try some things to see what is wrong over here. Thanks for the answer.

**Comment by o-b-o** [comment]
Alright, I did some testing. I tried using different devices, different internet connection and even a proxy from the netherlands, but I wasn't able to connect.

**Comment by o-b-o** [comment]
I don't know what the problem was but it's gone.
