### ISSUE TITLE
[Question] How can I change plot color ?

### ISSUE THREAD

**Issue by T1mL3arn** [ChristopherChudzicki/math3d-react#306]
Any surface I created has the same color (blue). How can I change it?
![image](https://user-images.githubusercontent.com/9349164/133868246-50c248d1-2495-4fbb-8c43-e95087cdd065.png)

**Comment by yodaldevoid** [comment]
I found that you need to click and hold on the color dot to bring up a menu to change the plot color. Just clicking toggles the plot.

This was definitely not obvious, though it makes a little more sense with touch controls.
