### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by xinyishen348** [ChristopherChudzicki/math3d-react#315]
Hi, I'm a high school student currently working on a math project and I used this wonderful easy-to-use tool to do the visualization section. I just want to know if there's any way I can cite your repository since citation for the project is a requirement. Thank you!

**Comment by ChristopherChudzicki** [comment]
Hi @xinyishen348 I realize this reply might be too late for your school project, but: As far as I am concerned, there's no need for a formal citation, though your teacher might have other requirements as far as citing websites. 

But if you have found the site helpful, do tell your fellow students / teacher!
