### ISSUE TITLE
Share Links aren't working

### ISSUE THREAD

**Issue by oneteaches2learn** [ChristopherChudzicki/math3d-react#325]
I have a few dozen math3D links that link to demonstrations that I've built for a vector calculus class. Those links are now no longer working, as of just today. I also tested a few brand new "share" links, and they are also not working. Instead of linking to the specific file, they just lead to the generic Math3D page.

**Comment by BB2CN** [comment]
same here man, I lost my trajectory model that was prepared for my math class today. 
I really appreciate the web creator, I know we shouldn't be demanding anything since it's free, but this is frustrating

**Comment by PalpatineSWU** [comment]
Lost the map of the galaxy for our server
F for all the lost data today

**Comment by o-b-o** [comment]
It finally happened. 

Welp, this is why running a local node is so important if you want to keep your models. 

F

There is a little extra to this issue. Sharing is broken too. Everything returns the pringles thang.

**Comment by o-b-o** [comment]
This makes rebuilding a database of math3d models much more important. I'll try to make a local node to see if that works.

**Comment by ChristopherChudzicki** [comment]
Looking into this.

**Comment by ChristopherChudzicki** [comment]
@oneteaches2learn Thanks for alerting me about this, it should be resolved now. (Working for me).

Thanks again for reporting!

**Comment by o-b-o** [comment]
Can confirm this is working again, the old graphs are back and share works as intended.

https://www.math3d.org/USKVBgU8X

**Comment by o-b-o** [comment]
Thanks for being so quick. You're awesome!

**Comment by oneteaches2learn** [comment]
Can also confirm it's working. Thanks for the fast response! Also, I love this tool and use it constantly; I would be interested in helping in ways that I can. So: What is a local node? Can I run one from my personal computer? And will that help this project?

**Comment by o-b-o** [comment]
Running a local node implies following the installation instructions on the repo README. Essentialy it means that you run an instance of math3d and the graphs are saved on your database.
