### ISSUE TITLE
Any way to export graphs without a link?

### ISSUE THREAD

**Issue by adin04** [ChristopherChudzicki/math3d-react#339]
I made a set of graphs in Math3D for a writing project and I want to put gifs of them into my project, probably just the camera spinning around on the x and y axes while looking from an angle. An image would also be okay, but I don't think a link will do. If no one responds I'll just use printscreen.

**Comment by ChristopherChudzicki** [comment]
Links are the only "export"-esque functionality at the moment. I'd suggest using a screenshot if you want a picture. If you want a gif, I've had good luck with https://giphy.com/apps/giphycapture as a generic screen gif recorder.

**Comment by adin04** [comment]
Thanks for your help! Much appreciated
