### ISSUE TITLE
how do I take a component of vector?

### ISSUE THREAD

**Issue by v-alisei** [ChristopherChudzicki/math3d-react#354]
Say I have a function f(x,y,z)=[-y,x,z]
how do I take i-th vector parameter? 
f(x,y,z).x doesn't work...

**Comment by v-alisei** [comment]
oh, I got it)
just use [f(x,y,z)[1],0,0]

**Comment by ChristopherChudzicki** [comment]
@v-alisei Another good option is dot products... `[f(x, y, z) * i, 0, 0]`. Or, depending on the circumstance, define the components of `f` separately.
